/*
 * generated by Xtext
 */
package net.vtst.ow.eclipse.soy.formatting;

import java.io.IOException;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting.IFormatter;
import org.eclipse.xtext.parsetree.reconstr.ITokenStream;

public class SoyFormatter implements IFormatter {
  
  private class TokenStream implements ITokenStream {
    
    private ITokenStream outputStream;

    public TokenStream(ITokenStream outputStream) {
      this.outputStream = outputStream;
    }

    public void flush() throws IOException {
      outputStream.flush();
    }

    public void writeHidden(EObject grammarElement, String value) throws IOException {
      outputStream.writeHidden(grammarElement, value);
    }

    public void writeSemantic(EObject grammarElement, String value) throws IOException {
      outputStream.writeSemantic(grammarElement, value);
    }
  }

  public ITokenStream createFormatterStream(String initalIndentation, ITokenStream outputStream, boolean preserveWhitespaces) {
    return new TokenStream(outputStream);
  }
}
