/*
* generated by Xtext
*/
package net.vtst.ow.eclipse.soy.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SoyProposalProvider extends AbstractSoyProposalProvider {

}
