/*
* generated by Xtext
*/
package net.vtst.ow.eclipse.soy.ui.outline;

import net.vtst.ow.eclipse.soy.soy.SoyFile;
import net.vtst.ow.eclipse.soy.soy.Template;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

/**
 * customization of the default outline structure
 * 
 */
public class SoyOutlineTreeProvider extends DefaultOutlineTreeProvider {
  
  // Create the root node
  protected void _createChildren(DocumentRootNode parentNode, SoyFile obj) {
    createNode(parentNode, obj);
  }
  
  // The root node (StyleSheet)
  protected void _createChildren(IOutlineNode parentNode, SoyFile obj) {
    for (Template template: obj.getTemplate()) {
      createNode(parentNode, template);
    }
  }
  protected boolean _isLeaf(SoyFile obj) {
    return obj.getTemplate().isEmpty();
  }

  // By default, elements are leafs.
  protected void _createChildren(IOutlineNode parentNode, EObject modelElement) {}
  protected boolean _isLeaf(EObject modelElement) {
    return true;
  }

}
